FROM amazoncorretto:8-al2-jdk

WORKDIR /app
#COPY /target/fleetman-0.0.1-SNAPSHOT.jar webapp.jar

EXPOSE 8080

CMD ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "webapp.jar"]