
FROM tomcat:9.0.98-jdk8-temurin-jammy

#MAINTAINER "Richard Chesterwood"

RUN rm -rf /usr/local/tomcat/webapps/*

COPY ./target/fleetman-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war

ENV JAVA_OPTS="-Dspring.profiles.active=docker-demo"

# Transfer our WAR
EXPOSE 8080

CMD ["catalina.sh", "run"]